<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HPEliteBook" ignored="0" name="Test_Demo1" tests="5" failures="1" timestamp="2023-01-19T23:30:54 SGT" time="4.135" errors="0">
  <testcase name="testcase001" time="1.023" classname="testngdemo.TestNGDemo"/>
  <testcase name="testcase002" time="1.009" classname="testngdemo.TestNGDemo"/>
  <testcase name="testcase003" time="1.018" classname="testngdemo.TestNGDemo"/>
  <testcase name="testcase004" time="0.004" classname="testngdemo.TestNGDemo">
    <failure type="java.lang.AssertionError" message="expected [4] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [1]
at testngdemo.TestNGDemo.testcase004(TestNGDemo.java:124)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testcase004 -->
  <testcase name="testcase005" time="1.002" classname="testngdemo.TestNGDemo"/>
</testsuite> <!-- Test_Demo1 -->
